version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 20
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 3.4641016
leavesCullingMode = "GAP"
leavesCullingAmount = 2
includeMangroveRoots = true
powderSnowCulling = true
endGatewayCulling = true
beaconBeamCulling = true
entityModelCulling = false
useOnModdedBlocksByDefault = true

[modCompatibility]
azurelib = true
everycomp = true
mcwfences = true
farmersdelight = true
bountiful = true
mcwroofs = true
blast = true
infinitybuttons = true
alloy_forgery = true
doapi = true
mcwwindows = true
betternether = true
oceansdelight = true
hamsters = true
galosphere = true
betterend = true
another_furniture = true
friendsandfoes = true
runes = true
gravity_changer = true
legacies_and_legends = true
aquamirae = true
earlystage = true
dramaticdoors = true
stoneworks = true
comforts = true
snowyspirit = true
chalk = true
duckling = true
mcwpaths = true
mcwtrpdoors = true
mcwbridges = true
mythic_charms = true
magistuarmory = true
lunade = true
the_bumblezone = true
milk = true
amendments = true
goated = true
advancementframes = true
snowrealmagic = true
walkietalkie = true
bakery = true
hybrid-aquatic = true
spell_engine = true
customportalapi = true
naturalist = true
mcwdoors = true
deeperdarker = true
botania = true
supplementaries = true
portablehole = true
endrem = true
grassoverhaul = true
amethystgravity = true
chipped = true
paladins = true
clutter = true
sawmill = true
create = true
geodes = true
windchimes = true
echochest = true
ironchest = true
placeitem = true
minecraft = true
fwaystones = true
extractinator = true
snifferplus = true
betterarcheology = true
underground_jungle = true
voidz = true
nethervinery = true
wetlands = true
numismatic-overhaul = true
jewelry = true
adventurez = true
bosses_of_mass_destruction = true
decorative_blocks = true
archers = true
amarite = true
universal_graves = true
xercamusic = true
moyai = true
villagersplus = true
vinery = true
carpeted = true
illagerinvasion = true
expandeddelight = true
grapplemod = true
